version: '3'

services:
  mysql:
    container_name: mysql-tareas-asir
    # command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: tareas
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
